name: Issue welcome commenter
permissions:
    issues: write
on: 
    issues:
        types: [opened]

jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            - name: "Dump Github context"
              run: echo "${{ toJson(github.event) }}"
